#server:
#  port: 20000
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: 'p6e-cloud-gateway-service'
#  config:
#    import: D://env/p6e.yml
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: false
#          lower-case-service-id: true
#
#logging:
#  config: 'classpath:p6e-cloud-logback.xml'
