server:
  port: 28000

spring:
  application:
    name: 'p6e-cloud-websocket-service'
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: '123456'
      lettuce:
        pool:
          max-wait: 10000
          max-idle: 8
          min-idle: 0
          max-active: 8

logging:
  config: 'classpath:p6e-cloud-logback.xml'

p6e:
  cloud:
    websocket:
      configs:
        - port: 9898
          type: 'TEXT'
          name: 'p6e-cloud-message'
