server:
  port: 20000

spring:
  profiles:
    active: dev
  application:
    name: 'p6e-cloud-gateway-service'
  config:
    import: D://env/p6e.yml

logging:
  config: 'classpath:p6e-cloud-logback.xml'
